app:
    package: com.grooveyman.crud
    page-size: 10
    
spring:
    application:
        name: crud
    datasource:
        url: jdbc:mysql://localhost:3306/store_api
        username: root
        password: JLoopz419#
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        